### ISSUE TITLE
Create a RJSProcess class

### ISSUE THREAD

**Issue by ilyasst** [ets-lipec/processes-modelling#18]
Currently, the code is structured as a set of scripts that contain functions. This issue is part of several that aim at re-writing the code using classes.

Create a file called `process.py` that will contain a class called `RJSProcess`. A `RJSProcess( RJSMachine, Polymer )` class will take as an input a `RJSMachine` object (an instance of `RJSMachine`) and a `Polymer` object; it will have several methods (class functions) that can return the various quantities of interest if requested by the user.

**Comment by AmelieLaurens** [comment]
process.py will replace the modelling.py of the previous issue ?
"The various quantities" you are talking about are graphics?

**Comment by ilyasst** [comment]
Was solves in PR #19
