### ISSUE TITLE
Machine parameters

### ISSUE THREAD

**Issue by jaklengaigne** [ets-lipec/processes-modelling#7]
In order to initialize machine parameters it would be best to use a file to load the parameters.
This would also be useful when running different scripts for the same machine and maybe also for the future models we implement.
The file should contain all the necessary parameters, as well as some general data about the machine itself (e.g. manufacturer).

**Comment by ilyasst** [comment]
#14 proposes an implementation for this

**Comment by ilyasst** [comment]
Solved in https://github.com/ets-lipec/processes-modelling/pull/16
