### ISSUE TITLE
Polymer parameters

### ISSUE THREAD

**Issue by jaklengaigne** [ets-lipec/processes-modelling#8]
In the same direction as the machine parameters, we should implement polymer properties as a file. 
This would also be useful when running different scripts for the same polymer and maybe also for the future models we implement.
The file should contain all the necessary properties (e.g. viscosity, surface tension), as well as some general data about the polymer itself (e.g. supplier, type, microstructure).

**Comment by ilyasst** [comment]
See the `Deck` class used here https://github.com/ets-lipec/consolidation-works/blob/master/consolidate/IO/deck.py or here https://github.com/ets-lipec/fdm-consolidation/blob/master/problem_1D/data/deck.py

@EthanCabon could you organize a call with @AmelieLaurens to present the YAML deck you and Andre ?

**Comment by ilyasst** [comment]
#13 proposes an implementation for this.

**Comment by ilyasst** [comment]
Solved in https://github.com/ets-lipec/processes-modelling/pull/16
